### ISSUE TITLE
桌面客户端运行内核时出现乱码

### ISSUE THREAD

**Issue by Earth-Bill** [JKerbin/Zhiyin-Butler-Opensource#1]
我将客户端内核程序使用pyinstaller打包之后复制到Zhiyin-Desktop/bin目录下并使用npm run dev命令运行该项目，然而控制台内所有中文全部呈现为乱码，如图所示。
![image](https://github.com/user-attachments/assets/1445b553-94e7-415e-9d03-6e145ccd82d3)

请问这个问题应该如何解决？

**Comment by JKerbin** [comment]
这个是nodejs调用windows启动子进程api时由于Unicode和utf-8编码转换错误造成的，建议调试完内核程序后再复制到Zhiyin-Desktop/bin目录下，而不是在Desktop中调试，这样可以节约您的开发时间，并且更不容易出现问题。

解决这个问题，您可以在Windows-设置-时间和语言-语言和区域-管理语言设置-非Unicode程序的语言-更改系统区域设置中，启用Beta版：使用Unicode UTF-8 提供全球语言支持功能，

如图所示：
![image](https://github.com/user-attachments/assets/dfdcdad1-e0dd-4aaa-8e62-8f43f964146e)

同时，请修改Zhiyin-Desktop/src/main/index.ts的第93、94行代码，注释掉第93行：
```
const output = iconv.decode(data, 'gbk');
```
同时取消对94行的注释：
```
const output = data.toString()
```
如图所示：
![image](https://github.com/user-attachments/assets/cd47c4ff-4f17-4d9e-b832-ef14e60b4c37)

另外，由于取消了对iconv-lite库的调用，请注释掉Zhiyin-Desktop/src/main/index.ts第6行：
```
const iconv = require('iconv-lite');
```
否则会在您使用
```
npm run build:win
```
指令对项目进行打包时报错。

希望可以解决您所遇到的问题，感谢您对本项目的关注~

**Comment by Earth-Bill** [comment]
问题已解决，感谢
